// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const DeleteMCPServerResponse: core.serialization.ObjectSchema<
    serializers.DeleteMCPServerResponse.Raw,
    TrueForge.DeleteMCPServerResponse
> = core.serialization.object({});

export declare namespace DeleteMCPServerResponse {
    export type Raw = {};
}
