// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConfiguredModel } from "./ConfiguredModel.js";
import { ModelProviderAuth } from "./ModelProviderAuth.js";

export const OpencodeGoModelProvider: core.serialization.ObjectSchema<
    serializers.OpencodeGoModelProvider.Raw,
    TrueForge.OpencodeGoModelProvider
> = core.serialization.object({
    auth: ModelProviderAuth,
    baseUrl: core.serialization.property("base_url", core.serialization.string().optional()),
    models: core.serialization.list(ConfiguredModel),
    type: core.serialization.stringLiteral("opencode-go"),
});

export declare namespace OpencodeGoModelProvider {
    export interface Raw {
        auth: ModelProviderAuth.Raw;
        base_url?: string | null;
        models: ConfiguredModel.Raw[];
        type: "opencode-go";
    }
}
